name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  once:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
  build:
    name: Publish for ${{ matrix.os }}
    needs: once
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [linux, windows, macos]

        include:
          - name: linux
            os: ubuntu-latest
            executable_name: fse
          - name: windows
            os: windows-latest
            executable_name: fse.exe
          - name: macos
            os: macos-latest
            executable_name: fse

    steps:
    - uses: actions/checkout@v1

    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: stable

    - name: Build
      run: |
        nimble install -y
        nim cc -o="${{ matrix.executable_name }}" src/main.nim

    - name: Create Archive
      run: tar -czvf fse-${{ matrix.name }}-${{ github.sha }}.tar.gz ${{ matrix.executable_name }} README.md

    - name: Upload Archive to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ needs.once.outputs.upload_url }}
        asset_name: fse-${{ matrix.name }}-${{ github.sha }}.tar.gz
        asset_path: fse-${{ matrix.name }}-${{ github.sha }}.tar.gz
        asset_content_type: application/gzip
